import type { ThreadMessage } from '@/lib/storage/db'

export function textOf(m: ThreadMessage): string {
  return m.content
    .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
    .map((b) => b.text)
    .join('')
}

/** An assistant reply to a `debate` prompt. Synthesis replies are not debate turns. */
export function isDebateTurn(messages: ThreadMessage[], i: number): boolean {
  const m = messages[i]
  const prev = i > 0 ? messages[i - 1] : undefined
  return (
    !!m &&
    m.role === 'assistant' &&
    !!prev &&
    prev.role === 'user' &&
    prev.origin?.kind === 'debate'
  )
}

/** A synthetic user prompt generated by the debate loop (boilerplate, not user words). */
export function isDebatePrompt(m: ThreadMessage): boolean {
  return (
    m.role === 'user' &&
    (m.origin?.kind === 'debate' || m.origin?.kind === 'debate-synthesis')
  )
}

/** Text up to the first blank line. */
export function firstParagraph(text: string): { preview: string; truncated: boolean } {
  const trimmed = text.trim()
  const match = /\n\s*\n/.exec(trimmed)
  if (!match) return { preview: trimmed, truncated: false }
  return { preview: trimmed.slice(0, match.index).trim(), truncated: true }
}

/** First sentence, with leading markdown (verdict labels, bullets, headings) stripped. */
export function firstSentence(text: string): string {
  const line = text.trim().split('\n')[0] ?? ''
  const cleaned = line
    // headings, quotes, list markers (but not bold markers)
    .replace(/^(?:[#>\s]+|[-*+]\s+|\d+[.)]\s+)+/, '')
    // a bold "Verdict:" style label adds nothing to a headline
    .replace(/^\*\*(verdict|tl;?dr|summary|conclusion)\s*:?\*\*\s*:?\s*/i, '')
    .replace(/\*\*/g, '')
    .trim()
  const end = /[.!?](\s|$)/.exec(cleaned)
  return end ? cleaned.slice(0, end.index + 1) : cleaned
}

/**
 * A debate turn folds only once a later reply has actually started arriving,
 * so the turn the user is reading stays open through the next model's
 * connect + thinking gap.
 */
export function shouldCollapseDebateTurn(messages: ThreadMessage[], i: number): boolean {
  if (!isDebateTurn(messages, i)) return false
  for (let j = i + 1; j < messages.length; j++) {
    const m = messages[j]
    if (m.role === 'assistant' && textOf(m).length > 0) return true
  }
  return false
}
